### ISSUE TITLE
Possible Unhandled Promise Rejection:  TypeError: Cant create property 'exact' on string 'XXX'

### ISSUE THREAD

**Issue by ursnj** [TanStack/query#3963]
### Describe the bug

 WARN  Possible Unhandled Promise Rejection (id: 41):
TypeError: Cannot create property 'exact' on string 'CHATS'
TypeError: Cannot create property 'exact' on string 'CHATS'
    at find (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:162639:49)
    at getQueryData (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:163986:51)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:178435:45)
    at next (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:178288:73)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/535v146a/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/535v146a/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/535v146a/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:178267:36)
    at updateChatsUserStatus (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:178434:21)
    at userStatusHandler (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:145285:90)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166177:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:169307:17)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:169272:21)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:169128:22)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166177:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:165177:14)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:169128:22)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166177:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:165473:18)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:165173:21)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:169128:22)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166177:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166539:20)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166391:20)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:166177:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:168131:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:168127:18)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:168277:18)
    at call (native)
    at dispatchEvent (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:31988:31)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:33004:31)
    at apply (native)
    at emit (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:4690:42)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:5633:36)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:5357:31)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:5584:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:5356:21)

### Your minimal, reproducible example

Happening with latest react-query version, with 3.x.x was working fine

### Steps to reproduce

1, Upgrade to 4.x.x
2. Run the project it started throwing this warning,

### Expected behavior

There should not be any warning

### How often does this bug happen?

Every time

### Platform

OS: Android
React: 18.0.0
React Native: 0.69.3

### react-query version

4.0.10

### TypeScript version

4.4.4

**Comment by TkDodo** [comment]
You're not showing any reproduction
