### ISSUE TITLE
[broadcastQueryClient] TypeError: PQueue is not a constructor 

### ISSUE THREAD

**Issue by nunoplima** [TanStack/query#5535]
### Describe the bug

Hi everyone!

I'm using `"@tanstack/query-broadcast-client-experimental": "4.29.5"` everything is working as expected but I do get an error: ```error - unhandledRejection: TypeError: PQueue is not a constructor
    at _callee16$ (file:///[path-to-app]/node_modules/@tanstack/query-broadcast-client-experimental/node_modules/broadcast-channel/dist/esnode/methods/node.js:570:29)```
    
Is there any know fix for this issue?
Many thanks in advance,

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/ecstatic-dhawan-urkt30?file=%2Fpages%2F_app.tsx%3A1%2C1

### Steps to reproduce

Go to the codesandbox and check the terminal, you should see something like: ```error unhandledRejection: Error [TypeError]: PQueue is not a constructor
    at _callee16$ (file:///workspace/node_modules/broadcast-channel/dist/esnode/methods/node.js:570:29)```

### Expected behavior

No error.

### How often does this bug happen?

None

### Platform

- OS: MacOS
- browser: chrome

### Tanstack Query adapter

None

### TanStack Query version

^4.12.0

### TypeScript version

4.8.4

**Comment by TkDodo** [comment]
seems to be an issue specific to nextjs according to:

- https://github.com/sindresorhus/p-queue/issues/103#issuecomment-1407762785

If you want to contribute this, we can make the type to use configurable to the plugin?

https://github.com/pubkey/broadcast-channel#methods
