### ISSUE TITLE
Error on the webpage Graphql section

### ISSUE THREAD

**Issue by Indranil-R** [TanStack/query#6100]
### Describe the bug

I was checking out the website and found an error on the page.
I didn't know where else to report it, so I'm reporting it here. 

[tanstack.com/query/v3/docs/react/examples/basic-graphql-request](https://tanstack.com/query/v3/docs/react/examples/basic-graphql-request)

```
Application Error
TypeError: Cannot read properties of undefined (reading 'split')
    at f (https://tanstack.com/build/_shared/chunk-MR75NVDT.js:1:355)
    at Module.b (https://tanstack.com/build/routes/query/$version/docs/$framework/examples/$-CU55RCAZ.js:1:475)
    at Er (https://tanstack.com/build/_shared/chunk-2GY7PSPF.js:14:3346)
    at Ki (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:5:52842)
    at bs (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:9:8687)
    at Zs (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:9:933)
    at Wf (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:9:864)
    at ot (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:9:724)
    at hi (https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:7:10856)
    at https://tanstack.com/build/_shared/chunk-BTOPUOQ5.js:5:38670
```

### Your minimal, reproducible example

tanstack.com/query/v3/docs/react/examples/basic-graphql-request

### Steps to reproduce

1. Go to tanstack.com/query/v3/docs/react/examples/basic-graphql-request

### Expected behavior

It should not be giving an error

### How often does this bug happen?

None

### Screenshots or Videos

![image](https://github.com/TanStack/query/assets/87275536/8e8f9c36-045c-4026-b147-4fe67d341a90)

### Platform

- OS [Windows]
- Browser [Edge and chrome]

### Tanstack Query adapter

react-query

### TanStack Query version

v3

**Comment by judicaelandria** [comment]
your link is not right and mine's working; use this link instead
https://tanstack.com/query/v3/docs/react/examples/react/basic-graphql-request
